---
- name: Fail if required vars are not set
  fail:
  when: >
    username == None or username|length == 0

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400 # 1 day

- apt:
    name: sudo

- template:
    src: "{{ distribution_id|join('-') }}/etc/sudoers.d/username-nopassword-all.j2"
    dest: /etc/sudoers.d/ansible-{{ username }}"
    mode: 440
    owner: root
    group: root
  when: nopassword is defined and nopassword
